"""
scrapers/sites/initium.py

Extracts articles from Initium Media (端傳媒) tag/column RSS feeds, e.g.
https://theinitium.com/tag/opinion/rss/ for the 評論 (Opinion) tag.

Extraction method: standard RSS 2.0, generated by Ghost (meta-generator:
Ghost 6.65 -- confirmed from a live fetch of both the HTML tag page and
its /rss/ feed). This is the cleanest of the sites handled so far: no
embedded JSON blob to regex out, no CSS-selector HTML scraping, no
multi-step ID-resolution API dance. Every field this project needs is
directly present in well-formed RSS elements -- confirmed against a real
fetch of https://theinitium.com/tag/opinion/rss/, not assumed from RSS's
general spec.

Field mapping -- confirmed against the real feed:
    <title>       -> title. Plain text, no site-name or column-name
                     prefix baked in (unlike the rendered HTML page,
                     which shows "評論｜ ..." as a heading -- that prefix
                     is NOT present in the RSS <title>, so no stripping
                     needed here).
    <link>        -> url. Already the canonical article URL.
    <description> -> description. Confirmed to be a genuine short
                     editorial summary, not full article text and not
                     boilerplate -- matches what the user originally
                     expected for this source. (<content:encoded> also
                     carries full article HTML for some items, but is
                     deliberately NOT used, per the project's standing
                     "headline/description only" scope.)
    <dc:creator>  -> author. Clean, single value in every item observed
                     in the real feed -- no multi-author 、-joined or
                     comma-joined string seen here (unlike thepaper.cn),
                     so no splitting/cleaning logic is applied. If a
                     multi-author byline is ever observed in this feed,
                     revisit -- for now this is passed through as-is.
    <pubDate>     -> published_at. RFC 822 format with an explicit GMT
                     timezone, e.g. "Wed, 23 Sep 2026 23:00:53 GMT" --
                     no CST-assumption needed, unlike thepaper.cn /
                     yicai.com / tencent_news.py. Parsed with Python's
                     email.utils.parsedate_to_datetime, which handles
                     RFC 822 dates natively, then reformatted to ISO 8601.
    <media:content url="..." medium="image"/>
                  -> image_url. A plain, direct, already-sized image URL
                     -- no CDN/resize-proxy puzzle like ftchinese.com's
                     CloudFront/Thumbor setup. Used directly.
    <category>    -> extra["categories"], a list. Multiple per item
                     (e.g. 性別, 大陸, 社會, 評論) -- genuinely useful
                     topic/section tags, captured but not yet used
                     elsewhere in the pipeline.
    <guid>        -> extra["guid"]. Ghost's internal post id
                     (isPermaLink="false" -- confirmed not a URL, just an
                     opaque id). Not used as the dedup key (articles.url
                     already serves that per the DB schema), but kept
                     in case it's useful for detecting Ghost-side edits
                     to an already-seen article later.

Paywall note: every article observed in this feed/tag is marked 僅限會員
    ("Members only") on the rendered site. Per the user's explicit
    instruction, this scraper does NOT special-case or flag paywalled
    content in any way -- headline/description/author/image are all
    freely available in the RSS regardless of the article body being
    gated, which is exactly the data this project needs.

Multiple columns via multiple tags: Initium's RSS pattern
    (https://theinitium.com/tag/{tag-slug}/rss/) generalizes to any tag,
    not just "opinion" -- e.g. presumably /tag/international/rss/,
    /tag/society/rss/, etc, though only /tag/opinion/rss/ has actually
    been fetched and confirmed so far. fetch_column() takes the tag slug
    as a parameter rather than hardcoding "opinion", so adding more
    Initium columns to the registry should be a one-line config addition
    once another tag's RSS URL is confirmed to follow the same pattern.

CAVEATS:
  - Only tested against a live fetch of ONE feed (tag/opinion). Other
    tags/columns on this site are assumed, not confirmed, to share the
    same RSS structure.
  - No pagination handling -- confirmed from the fetched feed that it
    returns a bounded set of recent items (11 items in the real fetch)
    with no visible cursor/next-page mechanism in the RSS itself (unlike
    the HTML tag page, which does paginate via /page/2/ etc). This is
    normal RSS behavior (a feed is typically "recent N items", not a
    paginated archive) and is fine for a polling scraper -- just noting
    that fetch_column() has no way to fetch OLDER items than what's in
    the current feed, only what a future poll happens to still include.
"""

from __future__ import annotations

from email.utils import parsedate_to_datetime
from typing import Callable, Optional

import feedparser

from ..base import RawArticle

HttpGet = Callable[[str], str]


def fetch_column(tag_slug: str, http_get: HttpGet) -> list[RawArticle]:
    """
    Fetch and parse one Initium tag's RSS feed.

    tag_slug: the tag portion of the URL, e.g. "opinion" for
        https://theinitium.com/tag/opinion/rss/. Passed separately
        rather than a full URL so the registry entry stays readable.
    http_get: shared HTTP GET function, injected for testability.
    """
    feed_url = f"https://theinitium.com/tag/{tag_slug}/rss/"
    raw_xml = http_get(feed_url)
    parsed = feedparser.parse(raw_xml)

    articles = []
    for entry in parsed.entries:
        article = _parse_entry(entry)
        if article is not None:
            articles.append(article)
    return articles


def _parse_entry(entry) -> Optional[RawArticle]:
    title = entry.get("title")
    url = entry.get("link")
    if not title or not url:
        return None

    description = entry.get("description") or entry.get("summary") or None
    if description:
        description = description.strip()

    author = entry.get("author") or None  # feedparser maps dc:creator -> .author

    published_at = _normalize_published_at(entry.get("published"))

    image_url = None
    media_content = entry.get("media_content")  # feedparser's parsed form of <media:content>
    if media_content:
        image_url = media_content[0].get("url") or None

    categories = [tag["term"] for tag in entry.get("tags", []) if tag.get("term")]

    return RawArticle(
        title=title.strip(),
        url=url,
        description=description,
        image_url=image_url,
        published_at=published_at,
        author=author,
        raw_author_string=author,  # no cleaning applied -- see module docstring
        extra={
            "categories": categories,
            "guid": entry.get("id"),  # feedparser maps <guid> -> .id
        },
    )


def _normalize_published_at(pub_date: Optional[str]) -> Optional[str]:
    """
    Initium's <pubDate> is RFC 822 with an explicit GMT timezone, e.g.
    "Wed, 23 Sep 2026 23:00:53 GMT". Parsed and reformatted to ISO 8601
    -- unlike every other site handled so far, no timezone ASSUMPTION is
    needed here, since GMT is stated explicitly in the source data.
    """
    if not pub_date:
        return None
    try:
        dt = parsedate_to_datetime(pub_date)
        return dt.isoformat().replace("+00:00", "Z")
    except (TypeError, ValueError):
        # Malformed date -- don't crash the whole column fetch over one
        # bad timestamp; fetched_at remains as the fallback sort key.
        return None
